"""Add password

Revision ID: 074d0a22379c
Revises: 
Create Date: 2019-11-20 17:48:25.952157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074d0a22379c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
